### ISSUE TITLE
Bug in buggy branch

### ISSUE THREAD

**Issue by badger-99** [ichsansandy/capstone-htmlcssjs#2]
In the "buggy-capstone" branch, I noticed the mobile menu button is unresponsive. Upon closer inspection, I realized that in your JavaScript file, you miss matched the selector you use for the button from the one in your HTML file. 

- The button code in your HTML
   `<button type="button" class="mobile-menu-toggle dekstop-hidden" aria-controls="primary-navigation" aria-expanded="false">`

- The code used to capture it in your JS file
   `const mobileMenuToggle = document.querySelector('#mobile-menu-toggle');`

In the query selector you reference a "mobile-menu-toggle" ID while in the HTML file that label belongs to a Class and not an ID. I suggest you change your query selector to reference a Class instead of an ID. That should eliminate the bug.

**Comment by ichsansandy** [comment]
💯 💯 💯
Nicely Done @badger-99
